name: Sync Branches with Main

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Sync with Frontend Branch
        run: |
          git checkout frontend
          git pull origin frontend || echo "No changes to pull for frontend"
          git reset --hard origin/main
          git merge --squash origin/main || echo "No changes to merge for frontend"
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Squash merge changes from main into frontend"
            git push origin frontend || echo "Failed to push frontend branch"
          fi
          git reset --hard main
          git push origin frontend --force || echo "Failed to force push frontend branch"

      - name: Sync with Backend Branch
        run: |
          git checkout backend
          git pull origin backend || echo "No changes to pull for backend"
          git reset --hard origin/main
          git merge --squash origin/main || echo "No changes to merge for backend"
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Squash merge changes from main into backend"
            git push origin backend || echo "Failed to push backend branch"
          fi
          git reset --hard main
          git push origin backend --force || echo "Failed to force push backend branch"
